ALTER TABLE public.quotes
  ADD COLUMN IF NOT EXISTS accepted_at TIMESTAMPTZ NULL,
  ADD COLUMN IF NOT EXISTS accepted_via TEXT NULL,
  ADD COLUMN IF NOT EXISTS accepted_note TEXT NULL,
  ADD COLUMN IF NOT EXISTS rejected_at TIMESTAMPTZ NULL,
  ADD COLUMN IF NOT EXISTS rejected_via TEXT NULL,
  ADD COLUMN IF NOT EXISTS rejection_reason TEXT NULL;
