-- Link invoices created by recurring automation to their rule (template uses recurring_invoice_rules.source_invoice_id).

ALTER TABLE public.invoices
  ADD COLUMN IF NOT EXISTS recurring_rule_id UUID REFERENCES public.recurring_invoice_rules(id) ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS idx_invoices_recurring_rule_id
  ON public.invoices (recurring_rule_id)
  WHERE recurring_rule_id IS NOT NULL;

COMMENT ON COLUMN public.invoices.recurring_rule_id IS 'Set when this row was generated by recurring automation; template invoice is identified by recurring_invoice_rules.source_invoice_id.';
